# Generated by Django 5.2.11 on 2026-02-24 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('ecocash', 'EcoCash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reference_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('period_month', models.DateField(blank=True, help_text='Month this payment is for', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.resident')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('fee', 'Monthly Fee'), ('adjustment', 'Adjustment'), ('penalty', 'Penalty'), ('credit', 'Credit'), ('debit', 'Debit')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.payment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.resident')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_month', models.DateField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='statements/')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.resident')),
            ],
            options={
                'ordering': ['-statement_month'],
                'unique_together': {('resident', 'statement_month')},
            },
        ),
    ]
