# Generated by Django 5.2.11 on 2026-02-24 10:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='cluster',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='cluster_na',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='stand',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
