# Generated by Django 5.2.11 on 2026-02-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stand_cluster_stand_cluster_na_stand_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='last_payment_date',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
