# Generated by Django 5.2.11 on 2026-02-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_resident_current_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='monthly_fee',
        ),
        migrations.AddField(
            model_name='resident',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/photos/'),
        ),
    ]
