# Generated by Django 5.2.11 on 2026-02-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_propertyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('FINED', 'Fined'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
