# Generated by Django 5.2.11 on 2026-02-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_propertyreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
    ]
