# Generated by Django 5.2.11 on 2026-02-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_propertyreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('APPROVED', 'Approved')], default='OPEN', max_length=20),
        ),
    ]
