# Generated by Django 5.2.11 on 2026-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_propertyreport_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreport',
            name='image',
            field=models.ImageField(blank=True, default='reports/default.png', null=True, upload_to='reports/'),
        ),
    ]
