# Generated by Django 5.2.11 on 2026-02-19 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='propertyreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reportcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='reportimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='violationtype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyreport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyreport',
            name='violation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reporting.violationtype'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reporting.propertyreport'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reporting.propertyreport'),
        ),
        migrations.AddIndex(
            model_name='propertyreport',
            index=models.Index(fields=['status'], name='reporting_p_status_6806df_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreport',
            index=models.Index(fields=['house_number'], name='reporting_p_house_n_369574_idx'),
        ),
    ]
