# Generated by Django 5.2.11 on 2026-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_community_options_alter_propertyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyreport',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='propertyreport',
            name='reporting_p_status_6806df_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyreport',
            name='reporting_p_house_n_369574_idx',
        ),
        migrations.AddField(
            model_name='propertyreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
